import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { doc, getDoc } from 'firebase/firestore';
import { db } from '../../config/firebase';
import Header from '../../components/Header';
import { sampleInspectionReport } from '../../data/mockData';
import './Inspection.css';

export default function InspectionReport() {
  const { id } = useParams();
  const [report, setReport] = useState(sampleInspectionReport);
  const [booking, setBooking] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;

    async function loadReport() {
      if (!id || id === 'demo') {
        setLoading(false);
        return;
      }

      try {
        const snap = await getDoc(doc(db, 'bookings', id));
        if (!cancelled && snap.exists()) {
          const bookingData = { id: snap.id, ...snap.data() };
          setBooking(bookingData);
          if (bookingData.inspectionReport) {
            setReport({ ...sampleInspectionReport, ...bookingData.inspectionReport });
          }
        }
      } catch (error) {
        console.error('Report load error:', error);
      } finally {
        if (!cancelled) setLoading(false);
      }
    }

    loadReport();
    return () => {
      cancelled = true;
    };
  }, [id]);

  const getScoreClass = (score) => {
    if (score >= 8) return 'score-good';
    if (score >= 6) return 'score-ok';
    return 'score-bad';
  };

  const downloadReportPdf = () => {
    const rows = report.categories.map((cat) => `
      <tr>
        <td>${cat.name}</td>
        <td style="text-align:right;font-weight:700;color:${cat.score >= 8 ? '#35B857' : cat.score >= 6 ? '#F59E0B' : '#E53935'}">${cat.score}/10</td>
      </tr>
    `).join('');

    const html = `
      <!doctype html>
      <html>
        <head>
          <title>Inspection Report ${booking?.id || ''}</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 28px; color: #1f2937; }
            h1 { margin: 0 0 4px; font-size: 28px; }
            .muted { color: #6b7280; margin: 0 0 18px; }
            .score { display: flex; align-items: center; gap: 24px; padding: 22px; background: #f8fafc; border-radius: 16px; margin: 20px 0; }
            .circle { width: 110px; height: 110px; border-radius: 999px; border: 7px solid #35B857; display:flex; align-items:center; justify-content:center; flex-direction:column; font-size: 30px; font-weight: 800; }
            .circle small { font-size: 14px; color:#6b7280; font-weight: 400; }
            .condition { color:#35B857; font-size: 24px; font-weight: 800; margin:0 0 6px; }
            table { width:100%; border-collapse: collapse; margin-top: 20px; }
            td { padding: 16px 0; border-bottom: 1px solid #e5e7eb; font-size: 18px; }
            .footer { margin-top: 28px; font-size: 12px; color:#6b7280; }
            @media print { button { display:none; } body { padding: 0; } }
          </style>
        </head>
        <body>
          <h1>Inspection Report</h1>
          <p class="muted">Booking ID: ${booking?.id || id || 'N/A'}</p>
          <p class="muted">${booking?.car || ''}</p>
          <div class="score">
            <div class="circle">${report.overallScore}<small>/10</small></div>
            <div>
              <p class="condition">${report.condition}</p>
              <p class="muted">${report.conditionNote}</p>
            </div>
          </div>
          <table>${rows}</table>
          <p class="footer">Generated by Auto Pro</p>
          <script>
            window.onload = () => {
              window.print();
            };
          </script>
        </body>
      </html>
    `;

    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    window.open(url, '_blank');
    setTimeout(() => URL.revokeObjectURL(url), 30000);
  };

  return (
    <div className="screen screen-with-header" id="inspection-report-screen">
      <Header title="Inspection Report" rightAction={
        <button onClick={downloadReportPdf} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--gray-700)' }}>
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4"/>
            <polyline points="7 10 12 15 17 10"/>
            <line x1="12" y1="15" x2="12" y2="3"/>
          </svg>
        </button>
      } />
      <div className="screen-content">
        <h3 className="section-label">Overall Score</h3>
        {loading && <p className="text-gray text-small">Loading report...</p>}
        <div className="report-score">
          <div className="report-score-circle">
            <span className="report-score-value">{report.overallScore}</span>
            <span className="report-score-total">/10</span>
          </div>
          <div>
            <p className="report-condition">{report.condition}</p>
            <p className="report-condition-note">{report.conditionNote}</p>
          </div>
        </div>

        <div className="report-categories">
          {report.categories.map((cat, i) => (
            <div key={i} className="report-category">
              <span className="report-category-dot" style={{ background: cat.score >= 8 ? 'var(--green)' : cat.score >= 6 ? 'var(--orange)' : 'var(--primary-red)' }}></span>
              <span className="report-category-name">{cat.name}</span>
              <span className={`report-category-score ${getScoreClass(cat.score)}`}>{cat.score}<span className="text-gray text-small">/10</span></span>
            </div>
          ))}
        </div>
      </div>
      <div className="bottom-action">
        <button className="btn btn-primary" id="btn-download-report" onClick={downloadReportPdf}>
          Download Report (PDF)
        </button>
      </div>
    </div>
  );
}
